<%
  socket = [
    ENV["BOXEN_MYSQL_SOCKET"],
    "/var/run/mysql5/mysqld.sock",
    "/tmp/mysql.sock"
  ].detect { |f| f && File.exist?(f) }

  port = ENV["BOXEN_MYSQL_PORT"] || "3306"
%>

defaults: &defaults
  adapter: mysql2
  username: root
  password: hello
  encoding: utf8
<% if socket %>
  host: localhost
  socket: <%= socket %>
<% else %>
  host: 127.0.0.1
  port: <%= port %>
<% end %>

production:
  database: vega
  <<: *defaults

development:
  database: vega
  <<: *defaults

test:
  database: vega_test
  <<: *defaults
